trigger:
- master

pool:
  name: Default   # your self-hosted agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'   # install Node.js runtime
  displayName: 'Install Node.js'

- script: |
    npm install -g @azure/static-web-apps-cli
    swa deploy ./ --deployment-token $(deployment_token)
  displayName: 'Deploy Static Web App'
