trigger:
- master   # or master, depending on your branch name

pool:
  name: Default   # use your self-hosted agent

steps:
- checkout: self

- task: AzureStaticWebApp@0
  inputs:
    app_location: "/"            # root folder with index.html
    api_location: ""             # no API, leave blank
    output_location: ""          # no build output, leave blank
    azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
