trigger:
  branches:
    include:
      - master   # change to 'master' if your default branch is master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Deploy static HTML directly to Azure Static Web Apps
- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'                 # Root folder (where index.html is)
    output_location: '.'              # No build folder, deploy as-is
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
    skip_app_build: true
